export const SITE_TITLE = 'Carlos de la Cruz'
export const SITE_DESCRIPTION = 'Carlos&apos; personal website.'
export const SITE_URL = 'https://heyimcarlos.dev'
export const SOURCE_URL = 'https://github.com/heyimcarlos/portfolio'
export const EMAIL = 'me@heyimcarlos.dev'
export const CHAT_APP_URL = 'https://chat.heyimcarlos.dev'
